Repository sbriclot/fleet, pull requests merged in 2021-02, with the labels that each got.

#51 Cloudinary setup
  Gemfile
  Gemfile.lock
  app/controllers/invoices_controller.rb
  app/controllers/vehicles_controller.rb
  app/models/invoice.rb
  app/models/vehicle.rb
  config/environments/development.rb
  config/storage.yml
  db/migrate/20210202104238_create_active_storage_tables.active_storage.rb
  db/schema.rb
Labels: Feature Setup

#52 Invoice CRUD
  app/controllers/invoices_controller.rb
  app/models/invoice.rb
  app/views/invoices/_form.html.erb
  app/views/invoices/edit.html.erb
  app/views/invoices/index.html.erb
  app/views/invoices/new.html.erb
  app/views/invoices/show.html.erb
Labels: Back, Front

#61 Maintenance and Operation full CRUD
  app/controllers/maintenances_controller.rb
  app/controllers/operations_controller.rb
  app/javascript/components/operations/changeMaintenancePlan.js
  app/javascript/packs/application.js
  app/models/maintenance.rb
  app/models/operation.rb
  app/views/maintenance_plans/index.html.erb
  app/views/maintenances/_m_edit.html.erb
  app/views/maintenances/index.html.erb
  app/views/operations/_ops_edit.html.erb
  app/views/operations/index.html.erb
  app/views/vehicles/show.html.erb
Labels: Back, Front, User Story
